[username]
format = " [$user]($style)@"
show_always = true
style_root = "bold red"
style_user = "bold red"

[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

[character]
error_symbol = " [×](bold red)"
success_symbol = " [->](bold red)"

